version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    ports:
      - 5000:5000
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_ROOT}/cache
    depends_on:
      - redis
    links:
      - redis
    networks:
      - mangler-net
  
  textgen:
    build:
      context: ./textgen
      dockerfile: Dockerfile
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - cache:${MANGLER_ROOT}/cache
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_ROOT}/cache
    depends_on:
      - redis
      - textgen-worker
    links:
      - redis
    networks:
      - mangler-net

  textgen-worker:
    build:
      context: ./textgen
      dockerfile: Dockerfile.worker
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - cache:${MANGLER_ROOT}/cache
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_ROOT}/cache
      - ROOT=${MANGLER_ROOT}
    depends_on:
      - redis
    links:
      - redis
    networks:
      - mangler-net
  
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - mangler-net
  
volumes:
  uploads:
  generated:
  cache:
  redis_data:

networks:
  mangler-net:
    driver: bridge