version: '3.9'

services:
  frontend-build:
    build:
      context: .
      dockerfile: frontend/Dockerfile.build
    volumes:
      - frontend:/app/build
    environment:
      - BUILD_DIR=/app/build
    networks:
      - mangler-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    ports:
      - 5000:5000
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - frontend:${MANGLER_ROOT}/frontend
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - FRONTEND=${MANGLER_ROOT}/frontend

      # Remove this for production!
      - DEBUG=1
    depends_on:
      - frontend-build
      - redis
      - textgen
    links:
      - redis
      - textgen
    networks:
      - mangler-net
  
  textgen:
    build:
      context: ./textgen
      dockerfile: Dockerfile
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - cache:${MANGLER_ROOT}/cache
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_CACHE}
    depends_on:
      - redis
      - textgen-worker
    links:
      - redis
    networks:
      - mangler-net

  textgen-worker:
    build:
      context: ./textgen
      dockerfile: Dockerfile.worker
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - cache:${MANGLER_ROOT}/cache
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_CACHE}
      - ROOT=${MANGLER_ROOT}
      - WORKER=1
    depends_on:
      - redis
    links:
      - redis
    networks:
      - mangler-net

  textgen-beat:
    build:
      context: ./textgen
      dockerfile: Dockerfile.beat
      args:
        - MANGLER_ROOT=${MANGLER_ROOT}
    volumes:
      - uploads:${MANGLER_UPLOADS}
      - generated:${MANGLER_GENERATED}
      - cache:${MANGLER_ROOT}/cache
    environment:
      - REDIS_URL=${REDIS_URL}
      - UPLOADS=${MANGLER_UPLOADS}
      - GENERATED=${MANGLER_GENERATED}
      - CACHE=${MANGLER_CACHE}
      - ROOT=${MANGLER_ROOT}
    depends_on:
      - redis
    links:
      - redis
    networks:
      - mangler-net
  
  redis:
    image: redis
    volumes:
      - redis_data:/data
    hostname: redis
    networks:
      - mangler-net
  
volumes:
  uploads:
  generated:
  cache:
  redis_data:
  frontend:

networks:
  mangler-net:
    driver: bridge