version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/mangler
      - ./uploads:/usr/src/mangler/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - mangler-net
  
  textgen:
    build:
      context: ./textgen
      dockerfile: Dockerfile
    volumes:
      - ./textgen:/usr/src/mangler
      - ./uploads:/usr/src/mangler/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - mangler-net
  
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - mangler-net
  
volumes:
  redis_data:

networks:
  mangler-net:
    driver: bridge