[RateLimits]

# Rate limit for the /upload endpoint
Upload = "10/minute"


[FileLimits]

# Max file count in upload request
UploadFileCount = 10

# Max total file size that can be uploaded
MaxFileSize = 20971520  # 20 MiB


[Cleanup]

# Uploaded files will be removed every this many seconds
UploadsCleanupInterval = 1200

# Only uploaded files older than this many seconds will be removed
UploadsMinLifetime = 300

# Generated files will be removed every this many seconds
GeneratedCleanupInterval = 1200

# Only generated files older than this many seconds will be removed
GeneratedMinLifetime = 300