ARG MANGLER_ROOT
ARG PORT
FROM python:3.11

ARG MANGLER_ROOT

ENV ROOT=${MANGLER_ROOT}
WORKDIR ${ROOT}

COPY backend/requirements/worker.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ARG COMMON_PATH=${ROOT}/common/
COPY common/python/ ${COMMON_PATH}
WORKDIR ${COMMON_PATH}
RUN pip install --no-cache-dir .
WORKDIR ${ROOT}

COPY backend/ .

RUN chmod +x ./worker.sh
ENTRYPOINT [ "./worker.sh" ]