ARG MANGLER_ROOT
FROM python:3.11

ARG MANGLER_ROOT

WORKDIR ${MANGLER_ROOT}

COPY requirements/worker.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ./celery.sh