ARG MANGLER_ROOT
FROM python:3.11

ARG MANGLER_ROOT

WORKDIR ${MANGLER_ROOT}

COPY textgen/requirements/worker.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY textgen/ .

ARG COMMON_PATH=${MANGLER_ROOT}/common/
COPY common/python/ ${COMMON_PATH}
WORKDIR ${COMMON_PATH}
RUN pip install --no-cache-dir .
WORKDIR ${MANGLER_ROOT}

RUN chmod +x ./beat.sh
ENTRYPOINT [ "./beat.sh" ]