[FreqdictCache]

# Retry the text generation task this many times if the corresponding cache is locked (used by another task)
CacheLockedRetries = 5

# Wait this many seconds between task retries due to locked cache
RetryDelay = 5


[TextGeneration]

# Character buffer size. When the buffer gets full, its contents are flushed to the appropriate output file and task progress is updated.
BufferSize = 1024

# Max number of text generation retries when the generator gets stuck or something else happens
MaxGenRetries = 10


[Tasks]

# Time limit for text generation tasks in seconds
TimeLimit = 30

# Hard time limit for text generation tasks in seconds. If this gets exceeded, the task is terminated immediately.
HardTimeLimit = 40