[FreqdictCache]

# Retry the text generation task this many times if the corresponding cache is locked (used by another task)
CacheLockedRetries = 5

# Wait this many seconds between task retries due to locked cache
RetryDelay = 5


[TextAnalysis]

# Report progress every this many analysis steps performed
ProgressStep = 1024


[TextGeneration]

# Character buffer size. When the buffer gets full, its contents are flushed to the appropriate output file and task progress is updated.
BufferSize = 1024

# Max number of text generation retries when the generator gets stuck or something else happens
MaxGenRetries = 10

# Max number of characters to generate
MaxLength = 100000

# Max freqdict depth
MaxDepth = 10

# Range of valid temperatures
TemperatureRange = [-10, 10]


[Tasks]

# Time limit for text generation tasks in seconds
TimeLimit = 60

# Hard time limit for text generation tasks in seconds. If this gets exceeded, the task is terminated immediately.
HardTimeLimit = 80


[Cleanup]

# Cache files will be removed every this many seconds
CacheCleanupInterval = 1200

# Only cache files older than this many seconds will be removed
CacheMinLifetime = 300

# Generated files will be removed every this many seconds
# GeneratedCleanupInterval = 1200

# Only generated files older than this many seconds will be removed
# GeneratedMinLifetime = 300
